### ISSUE TITLE
The scan event only occurs after the user scans

### ISSUE THREAD

**Issue by lyleshaw** [lyleshaw/python-wechaty-puppet-itchat#5]
Before:
![image](https://user-images.githubusercontent.com/25427168/128282833-b45a263a-dfa2-4f0f-b267-192279df8e3f.png)
After:
![image](https://user-images.githubusercontent.com/25427168/128282871-0b70d87f-560e-4dac-8d8b-3ecb3470ffe8.png)

**Comment by wj-Mcat** [comment]
Great, it's a huge step for python-wechaty-puppet-itchat. Please go ahead.

**Comment by lyleshaw** [comment]
It seems that all the emit event will occurs after the itchat fuction has done.
eg:
1. scan event occurs after itchat::login::login function.
2. massage event occurs after itchat::login::start_receiving::exitCallback function has been called.
![image](https://user-images.githubusercontent.com/25427168/128834333-c83b2aac-e7f1-4951-ae90-764891d33171.png)

Those problems will make the on_scan and on_massage function (which in Wechaty) invalidated.
